var pp1 = new Pair($("#x_616"), $("#x_587"));
var pp2 = new Pair($("#x_616"), $("#x_558"));
var pp3 = new Pair($("#x_616"), $("#x_529"));
var pp4 = new Pair($("#x_616"), $("#x_500"));
var pp5 = new Pair($("#x_616"), $("#x_471"));
console.log(pp1.polar_angle_less_than(pp2));
console.log(pp2.polar_angle_less_than(pp1));
console.log("------------");
console.log(pp2.polar_angle_less_than(pp3));
console.log(pp3.polar_angle_less_than(pp2));
console.log("------------");
console.log(pp3.polar_angle_less_than(pp4));
console.log(pp4.polar_angle_less_than(pp3));
console.log("------------");
console.log(pp4.polar_angle_less_than(pp5));
console.log(pp5.polar_angle_less_than(pp4));
console.log("------------");



$("#x_371").click();
$("#x_342").click();
$("#x_429").click();
$("#x_458").click();
$("#x_487").click();
$("#x_400").click();
$("#x_373").click();
$("#x_404").click();
$("#x_435").click();
$("#x_466").click();
$("#x_497").click();
$("#x_528").click();
$("#x_527").click();
$("#x_526").click();
$("#x_525").click();
$("#x_524").click();
$("#x_523").click();
$("#x_522").click();
$("#x_521").click();
$("#x_520").click();
$("#x_519").click();
$("#x_518").click();
$("#x_517").click();